# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Package Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Branch Checkout âœ”
      uses: actions/checkout@v4

    - name: Setup Swift ðŸ¦‰
      uses: swift-actions/setup-swift@v2.2.0
      with:
        swift-version: "6"

    - name: Build ðŸ’»
      run: swift build -v

    - name: Test ðŸ§ª
      run: swift test -v 
